eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: student-service
    config:
        import: optional:configserver:http://localhost:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/micro_db
        username: postgres
        password: ******
    jpa:
        properties:
            hibernate:
                #show_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8090